version: '3.8'

services:
  # Servicio A 'El cerebro' (Flask)
  app:
    build: ./app
    container_name: flask_backend
    restart: always
    env_file:
      - .env
    # No abrimos puertos al exterior, solo vive en la red interna
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import urllib.request; urllib.request.urlopen(\"http://localhost:8000/health\")' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - uam_network

  # Servicio B: 'El Escudo' (Nginx)
  nginx:
    image: nginx:1.25
    container_name: nginx_proxy
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d # Conectamos el contenedor con el archivo de configuración
      - ./app/static:/app/static # Para que Nginx acceda a las fotos directamente1
    ports:
      - "80:80" # Mapeamos el puerto 80 (HTTP por defecto) real al 80 de Nginx
    depends_on: 
      app:
        # Punto de control para el orquestador (Docker). 
        # Permite verificar la disponibilidad del servicio   
        condition: service_healthy
    networks:
      - uam_network

  # Servicio C: Base de datos en memoria para sesiones seguras
  redis:
    image: redis:alpine
    container_name: redis_session
    restart: always
    # Activa el modo AOF
    command: ["redis-server", "--appendonly", "yes"] # Comprobamos que redis esté funcionando
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 15s
      timeout: 5s
      retries: 3
    # Mapea la base de datos de la RAM al disco duro real
    volumes:
      - ./redis_data:/data
    networks:
      - uam_network

networks:
  uam_network:
    driver: bridge # Switch virtual dentro del ordenador
    # Se pueden comunicar app y nginx sin saber ips gracias al DNS de Docker
