resolver 127.0.0.11 valid=30s;
server_tokens off;

# REDIRECCIÓN: Si alguien entra por http (puerto 80), lo mandamos a https (443)
server {
    listen 80;
    server_name moodle.uarn.es seif.eps.uam.es;
    return 301 https://$host$request_uri;
}

# ==========================================
# BLOQUE 1: LA TRAMPA (PHISHING)
# ==========================================
server {
    listen 443 ssl;
    server_name moodle.uarn.es; 

    ssl_certificate /etc/letsencrypt/live/moodle.uarn.es/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/moodle.uarn.es/privkey.pem;

    # 1. EL PARCHE DE SEGURIDAD: Bloqueamos la ruta del admin en el dominio falso
    location /ivan_alex_syf0954 {
        return 404; # Simulamos que esta página no existe
        access_log off; # Ni siquiera lo registramos para no hacer ruido
    }

    # 2. El tráfico normal va a Flask
    location / {
        set $backend_app app;

        proxy_pass http://$backend_app:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Tu ruta de estáticos dockerizada
    location /static/ {
        alias /app/static/;
        expires 30d;
        add_header Cache-Control "public, max-age=2592000";
    }

    # Tus bloqueos de OpSec
    location ~ /\.(env|git|ht) {
        deny all;
        access_log off;
        log_not_found off;
    }

    location ~* \.(py|sh|sql|yml)$ {
        deny all;
    }
}

# ==========================================
# BLOQUE 2: EL CONTROL (ADMIN DASHBOARD)
# ==========================================
server {
    listen 443 ssl; 
    # Atrapamos solo el dominio oficial de la UAM
    server_name seif.eps.uam.es; 

    ssl_certificate /etc/letsencrypt/live/moodle.uarn.es/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/moodle.uarn.es/privkey.pem;

    location / {
        set $backend_app app;

        proxy_pass http://$backend_app:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Tu ruta de estáticos dockerizada
    location /static/ {
        alias /app/static/;
        expires 30d;
        add_header Cache-Control "public, max-age=2592000";
    }

    # Tus bloqueos de OpSec
    location ~ /\.(env|git|ht) {
        deny all;
        access_log off;
        log_not_found off;
    }

    location ~* \.(py|sh|sql|yml)$ {
        deny all;
    }
    
}